author = "bill88t"
title = "Example config"
config_version = 1
uninstall_upon_completion = false
headless = false

[gui]
logo = false

[stages]
offline = ["Location", "Keyboard", "User", "Summary", "Install"]
online = ["Location", "Keyboard", "Desktop Environment", "Packages", "User", "Summary", "Install"]

[settings]
lang = "str"
kb_lang = ['a', 'b', 'c']

region = "en_us"
timezone = "Athens"

use_ntp = true

user = false
passwd = false
ssh_pub = false
root_passwd = false

[apps]
app_selection = []
greeter_enable = false

[postint]
type = 0
data = false

