install_type = "offline"
hostname = "breborb"
root_password = false
ntp = true

locale = "en_US"

packages = []
de_packages = []

[timezone]
region = "Europe"
zone = "Sofia"

[layout]
lang = "American English"
variant = "alt-intl"

[user]
fullname = "Bred guy"
username = "Panda"
password = "123"
uid = 1000
gid = false
shell = "/bin/zsh"
groups = ["wheel", "network", "video", "audio", "storage", "uucp"]
sudo_nopasswd = false
autologin = false

[installer]
shown_pages = ['Keyboard', 'Timezone', 'User', 'Locale']
installer_version = "0.1.0"
ui = "tui"
