install_type = "offline"
hostname = "breborb"
root_password = false
sudo_nopasswd = true
ntp = true

locale = "en_US"

[timezone]
region = "Europe"
zone = "Sofia"

[layout]
lang = "American English"
variant = "alt-intl"

[user]
fullname = "Bred guy"
username = "Panda"
password = "123"
uid = 1000
gid = false
shell = "/bin/zsh"
groups = ["wheel", "network", "video", "audio", "storage", "uucp"]
autologin = true

[installer]
shown_pages = ['Keyboard', 'Timezone', 'User', 'Locale']
packages = []
de_packages = []
