install_type = "offline"
hostname = "breborb"
root_password = false

locale = "en_US.UTF-8 UTF-8"

packages = []
de_packages = []

[timezone]
region = "Europe"
zone = "Sofia"
ntp = true

[layout]
model = "pc105"
layout = "us"
variant = "alt-intl"

[user]
fullname = "Bred guy"
username = "Panda"
password = "123"
uid = 1005
gid = false
shell = "/bin/bash"
groups = ["wheel", "network", "video", "audio", "storage", "uucp"]
sudo_nopasswd = false
autologin = false

[installer]
shown_pages = ['Keyboard', 'Timezone', 'User', 'Locale']
installer_version = "0.1.0"
ui = "tui"
